
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 08 23:48:48 CST 2022
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONTEXTUAL_OPERATOR = 57;
  public static final int CLASS_NAME = 59;
  public static final int CLOSING_KEY = 24;
  public static final int CONST = 38;
  public static final int NAMESPACE = 44;
  public static final int EQUALS = 11;
  public static final int CASE = 34;
  public static final int DATA_TYPE = 4;
  public static final int INTERFACE = 43;
  public static final int OUT = 46;
  public static final int FOR = 10;
  public static final int WRITE = 56;
  public static final int STATIC = 48;
  public static final int AND = 62;
  public static final int SUBSTRACTION = 13;
  public static final int SEMICOLON = 28;
  public static final int OR = 63;
  public static final int THROW = 50;
  public static final int CLASS = 36;
  public static final int RELATIONAL_OPERATOR = 17;
  public static final int MAIN = 27;
  public static final int IF = 6;
  public static final int ABSTRACT = 32;
  public static final int EOF = 0;
  public static final int OPENING_KEY = 23;
  public static final int SYSTEM = 53;
  public static final int RETURN = 47;
  public static final int NEW = 58;
  public static final int error = 1;
  public static final int CLOSING_SQUARE_BRACKET = 26;
  public static final int LINE = 2;
  public static final int TRY = 51;
  public static final int NULL = 45;
  public static final int NUMBER = 30;
  public static final int INCREASE_OPERATOR = 19;
  public static final int BREAK = 33;
  public static final int VOID = 52;
  public static final int FINALLY = 40;
  public static final int ERROR = 31;
  public static final int OP_ARITMETICA = 61;
  public static final int SWITCH = 49;
  public static final int ATRIBUTION_OPERATOR = 18;
  public static final int WRITELINE = 54;
  public static final int FOREACH = 41;
  public static final int ELSE = 7;
  public static final int BOOLEAN_OPERATOR = 20;
  public static final int GOTO = 42;
  public static final int OPENING_SQUARE_BRACKET = 25;
  public static final int FINAL = 37;
  public static final int WHILE = 9;
  public static final int DEFAULT = 39;
  public static final int SUM = 12;
  public static final int STRING = 5;
  public static final int QUOTES = 3;
  public static final int LOGICAL_OPERATOR = 16;
  public static final int DIVISION = 15;
  public static final int OPENING_PARENT = 21;
  public static final int CLOSING_PARENT = 22;
  public static final int VAR = 60;
  public static final int MULTIPLICATION = 14;
  public static final int CONSOLE = 55;
  public static final int DO = 8;
  public static final int CATCH = 35;
  public static final int IDENTIFIER = 29;
}

